# fly.toml app configuration file generated for thought-bot on 2025-03-17T12:53:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thought-bot'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
